### PR TITLE
avoid updating standard scopes

### LINKED ISSUE #163: `authlete_service` Resource Shows Unnecessary Changes in supported_scopes After Apply
Hi there,

When using the authlete_service resource to manage an Authlete service, the supported_scopes attribute shows unnecessary changes after running terraform apply followed by terraform plan. This results in a recreation of the resource being detected even though there are no actual changes made to the resource. This issue specifically occurs when the name attribute of supported_scopes is set to "openid".

### Terraform Version

```
Terraform v1.8.5
on darwin_arm64
+ provider registry.terraform.io/authlete/authlete v1.3.14
```

### Affected Resource(s)
- authlete_service

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    authlete = {
      source  = "authlete/authlete"
      version = "~> 1.3.14"
    }
  }
}

resource "authlete_service" "this" {
  issuer                   = "https://as.mydomain.com"
  service_name             = "MyDomainAS"
  description              = "A terraform based service for managing the Authlete based OAuth server"
  supported_grant_types    = ["AUTHORIZATION_CODE"]
  supported_response_types = ["CODE"]

  supported_scopes {
    name          = "openid"
    default_entry = false

    descriptions {
      tag   = "en"
      value = "A permission to request an OpenID Provider to issue an ID Token. See OpenID Connect Core 1.0, 3.1.2.1. for details."
    }
    descriptions {
      tag   = "ja"
      value = "OpenID プロバイダーに ID トークンの発行を要求するための権限です。詳細は OpenID Connect Core 1.0, 3.1.2.1. を参照してください。"
    }
  }
  scope_required = true
}
```

### Expected Behavior

After running terraform apply, running terraform plan should show no changes if there have been no modifications to the configuration.

### Actual Behavior

After running terraform apply, running terraform plan shows the following changes, indicating a recreation of the resource:

```
Terraform will perform the following actions:

  # module.authlete_service.authlete_service.this will be updated in-place
  ~ resource "authlete_service" "this" {
        id                                               = "978129159511"
        # (131 unchanged attributes hidden)

      - supported_scopes {
          - default_entry = false -> null
          - description   = "A permission to request an OpenID Provider to issue an ID Token. See OpenID Connect Core 1.0, 3.1.2.1. for details." -> null
          - name          = "openid" -> null

          - descriptions {
              - tag   = "en" -> null
              - value = "A permission to request an OpenID Provider to issue an ID Token. See OpenID Connect Core 1.0, 3.1.2.1. for details." -> null
            }
          - descriptions {
              - tag   = "ja" -> null
              - value = "OpenID プロバイダーに ID トークンの発行を要求するための権限です。詳細は OpenID Connect Core 1.0, 3.1.2.1. を参照してください。" -> null
            }
        }
      + supported_scopes {
          + default_entry = false
          + name          = "openid"
            # (1 unchanged attribute hidden)

          + descriptions {
              + tag   = "en"
              + value = "A permission to request an OpenID Provider to issue an ID Token. See OpenID Connect Core 1.0, 3.1.2.1. for details."
            }
          + descriptions {
              + tag   = "ja"
              + value = "OpenID プロバイダーに ID トークンの発行を要求するための権限です。詳細は OpenID Connect Core 1.0, 3.1.2.1. を参照してください。"
            }
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce

1. Apply the provided Terraform configuration using terraform apply.
2. Run terraform plan immediately after.

### PR DESCRIPTION
**Pull request by YoloZoloo**

### CODE REVIEW

**Comment by YoloZoloo** [comment]
closes #163

**Comment by dcreado** [comment]
let me comment here for visibility.
I think that requiring every services managed by the terraform provider to include that list of standard scopes is not reasonable.
The full list of supported scopes should be as the service console, where it is up to the customer to decide without any constraint it.
The not empty change list seems to be a different problem and marking the tests to ignore, will not fix issue.

**Comment by YoloZoloo** [comment]
@dcreado, all valid points. If you have a good alternative solution, we can implement your idea.

As mentioned in https://github.com/authlete/terraform-provider-authlete/issues/163, `terraform apply` yields a non-empty plan because the Authlete server treats the standard scopes slightly differently than the custom scopes. 
If we put `openid` or `email` in the scope's name field, the Authlete server will enable those scopes. The main culprit is what Authlete responds to the get-service requests. The get-service response includes the standard scopes, which have the predefined value in the description, attributes, and default_entry, along with everything that is related to that standard scope. The terraform plan will not be empty if this predefined value doesn't match what the terraform configuration defines. 

1. We can force the developers to write the standard scopes in an exact way that conforms to the Authlete's behavior.
2.  Or suppress the non-empty plan.

**Comment by dcreado** [comment]
I think the problem is that we are replacing the supported scope array of the schema.ResourceData when syncing the server -> local definition.... as the object is a different one, terraform will report that the plan is not empty.

**Comment by dcreado** [comment]
@YoloZoloo I've changed the implementation and noticed a quiet odd behavior of API server... When creating the service, the API auto populate the descriptions and description attributes of the "standard" supported scopes.

Marking the "description" as computed fix the problem for that attribute, but for the "descriptions" there will not work.

I think there are some options:
- we stop syncing after creation those attributes
- We can either submit a patch to API removing those attributes after creation of the service if the "standard" scope are included
- We implement a Customdiff to review the ResourceDiff and delete from the plan changes on descriptions for "standard" attributes
- We change the API server to stop inserting the descriptions that were not defined by the user.

The second one seems to me the best, as we force the supported_scope to match the definition of terraform resource.

**Comment by YoloZoloo** [comment]
Yes. The behavior you described is what I tried to circumvent in this PR. As we both agree that the Authlete API treats standard scopes differently than other scopes. 

As for the mentioned solutions, I would opt for the third one. The second approach seems a bit intrusive to Authlete code base. Let's first decide on which approach is the most suitable, then work it from there.

**Comment by dcreado** [comment]
@YoloZoloo I've pushed a skeleton for 3rd option.

**Comment by YoloZoloo** [comment]
@dcreado Thanks for the skeleton. I made a few changes based on your code and pushed the new code. Can you review it and share your opinion?

**Review by dcreado — APPROVED** [review]
approved

**Pull request merged**
